{
    'name': 'Account Preview Reports',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'Adds Preview to Accounting Reports',
    'author': 'SIMI Technologies',
    'website': 'https://simitechnologies.co.ke',
    'depends': ['account', 'base_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',

        'views/profit_and_loss.xml',
        'views/bank_book_preview.xml',
        'views/cash_book_preview.xml',
        'views/day_book_preview.xml',
        'views/aged_partner.xml',
        'views/partner_ledger.xml',
        'views/general_ledger.xml',
        'views/trial_balance.xml',
        'views/tax_report.xml',
        'views/journal_audit.xml',

        'wizards/profit_and_loss.xml',
        'wizards/cash_flow_statement_wizard.xml',
        'wizards/bank_book.xml',
        'wizards/cash_book.xml',
        'wizards/day_book.xml',
        'wizards/aged_partner.xml',
        'wizards/partner_ledger.xml',
        'wizards/general_ledger.xml',
        'wizards/trial_balance.xml',
        'wizards/tax_report.xml',
        'wizards/journal_audit.xml',
    ],
    'installable': True,
    'application': True,

    'images': ['static/description/images/icon.png'],
}
